export const ActionTypes = {
    SET_BLOGS: "SET_BLOGS",
    SELECTED_BLOG: "SELECTED_BLOG",
    REMOVE_SELECTED_BLOG: "REMOVE_SELECTED_BLOG",
    SET_PROJECTS: "SET_PROJECTS",
    SELECTED_PROJECT: "SELECTED_PROJECT",
    REMOVE_SELECTED_PROJECT: "REMOVE_SELECTED_PROJECT",
};